export const
    NOT_LOADED = "NOT_LOADED",
    LOADING = "LOADING",
    LOADED = "LOADED",
    UNLOADED = "UNLOADED",
    LOADED_ERROR = "LOADED_ERROR";

export const
    NOT_SAVED = "NOT_SAVED",
    SAVING = "SAVING",
    SAVED = "SAVED",
    SAVED_ERROR = "SAVED_ERROR";