export const NOT_LOGINED = "NOT_LOGINED",
	LOGINING = "LOGINING",
	UNLOGINING = "UNLOGINING",
	LOGINED = "LOGINED",
	UNLOGINED = "UNLOGINED",
	LOGINED_ERROR = "LOGINED_ERROR",
	UNLOGINED_ERROR = "UNLOGINED_ERROR";
